services:
  postgres:
    image: postgres:16-alpine
    container_name: freshful-api-postgres
    environment:
      POSTGRES_DB: freshful
      POSTGRES_USER: freshful
      POSTGRES_PASSWORD: freshful
    ports:
      - "5432:5432"
    volumes:
      - freshful-api-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U freshful -d freshful"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  freshful-api-postgres-data: